name: Build EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: دریافت کد از ریپازیتوری
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: نصب وابستگی‌ها
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: ساخت فایل exe
        run: |
          pyinstaller --onefile --windowed --name NobatDehi app.py

      - name: آپلود فایل exe
        uses: actions/upload-artifact@v4
        with:
          name: NobatDehi-Windows
          path: dist/NobatDehi.exe
